# Generated by Django 4.2 on 2023-04-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='subject',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
