# Generated by Django 4.2 on 2023-04-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ads',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='subject',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
