# Generated by Django 4.1.5 on 2023-05-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_activities_subject_alter_ads_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'verbose_name': 'نشاط او فعالية', 'verbose_name_plural': 'الانشطة والفعاليات'},
        ),
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'إعلان', 'verbose_name_plural': 'الإعلانات'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'خبر', 'verbose_name_plural': 'الاخبار'},
        ),
    ]
