# Generated by Django 4.1.5 on 2023-05-06 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_activities_options_alter_ads_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='image_ar',
            field=models.ImageField(blank=True, upload_to='activities/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='activities',
            name='subject_1_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 1'),
        ),
        migrations.AddField(
            model_name='activities',
            name='subject_2_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 2'),
        ),
        migrations.AddField(
            model_name='activities',
            name='subject_3_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 3'),
        ),
        migrations.AddField(
            model_name='activities',
            name='subject_4_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 4'),
        ),
        migrations.AddField(
            model_name='activities',
            name='subject_5_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 5'),
        ),
        migrations.AddField(
            model_name='activities',
            name='subject_ar',
            field=models.CharField(blank=True, max_length=500, verbose_name='موضوع'),
        ),
        migrations.AddField(
            model_name='activities',
            name='title_ar',
            field=models.CharField(default=1, max_length=40, verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ads',
            name='image_ar',
            field=models.ImageField(blank=True, upload_to='ads/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='ads',
            name='subject_1_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 1'),
        ),
        migrations.AddField(
            model_name='ads',
            name='subject_2_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 2'),
        ),
        migrations.AddField(
            model_name='ads',
            name='subject_3_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 3'),
        ),
        migrations.AddField(
            model_name='ads',
            name='subject_4_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 4'),
        ),
        migrations.AddField(
            model_name='ads',
            name='subject_5_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 5'),
        ),
        migrations.AddField(
            model_name='ads',
            name='subject_ar',
            field=models.CharField(blank=True, max_length=500, verbose_name='موضوع'),
        ),
        migrations.AddField(
            model_name='ads',
            name='title_ar',
            field=models.CharField(default=1, max_length=40, verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='image_ar',
            field=models.ImageField(blank=True, upload_to='news/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='news',
            name='subject_1_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 1'),
        ),
        migrations.AddField(
            model_name='news',
            name='subject_2_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 2'),
        ),
        migrations.AddField(
            model_name='news',
            name='subject_3_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 3'),
        ),
        migrations.AddField(
            model_name='news',
            name='subject_4_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 4'),
        ),
        migrations.AddField(
            model_name='news',
            name='subject_5_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 5'),
        ),
        migrations.AddField(
            model_name='news',
            name='subject_ar',
            field=models.CharField(blank=True, max_length=30, verbose_name='موضوع'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar',
            field=models.CharField(default=1, max_length=40, verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activities',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='image',
            field=models.ImageField(blank=True, upload_to='activities/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='subject',
            field=models.CharField(blank=True, max_length=500, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='subject_1',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 1'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='subject_2',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 2'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='subject_3',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 3'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='subject_4',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 4'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='subject_5',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 5'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='title',
            field=models.CharField(max_length=40, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(blank=True, upload_to='ads/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='subject',
            field=models.CharField(blank=True, max_length=500, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='subject_1',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 1'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='subject_2',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 2'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='subject_3',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 3'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='subject_4',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 4'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='subject_5',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 5'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(max_length=40, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subject',
            field=models.CharField(blank=True, max_length=30, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subject_1',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 1'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subject_2',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 2'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subject_3',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 3'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subject_4',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 4'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subject_5',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع 5'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=40, verbose_name='عنوان'),
        ),
    ]
