# Generated by Django 4.2 on 2023-04-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('detail_1', models.TextField(blank=True, max_length=400)),
                ('detail_2', models.TextField(blank=True, max_length=400)),
                ('detail_3', models.TextField(blank=True, max_length=400)),
                ('image', models.ImageField(blank=True, upload_to='buildingImage/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfectStu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(max_length=40)),
                ('detail', models.TextField(blank=True, max_length=400)),
                ('image', models.ImageField(blank=True, upload_to='perfectStudent/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
