# Generated by Django 4.2 on 2023-04-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univlife', '0002_buildinginfo_title_perfectstu_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfectstu',
            name='header',
            field=models.CharField(max_length=40),
        ),
    ]
