# Generated by Django 4.1.5 on 2023-04-23 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('univlife', '0003_alter_perfectstu_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinginfo',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='perfectstu',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
