# Generated by Django 4.1.5 on 2023-05-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univlife', '0004_buildinginfo_date_created_perfectstu_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildinginfo',
            options={'verbose_name': 'مبنى او منشاءة جامعية', 'verbose_name_plural': 'البيئة الجامعية'},
        ),
        migrations.AlterModelOptions(
            name='perfectstu',
            options={'verbose_name': 'طلاب اوائل', 'verbose_name_plural': 'الطلاب الاوائل'},
        ),
    ]
