# Generated by Django 4.1.5 on 2023-04-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnivTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.IntegerField(blank=True)),
                ('facebook', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
