# Generated by Django 4.1.5 on 2023-04-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='univteam',
            name='image',
            field=models.ImageField(blank=True, upload_to='Team/%y/%m/%d'),
        ),
    ]
