# Generated by Django 4.2 on 2023-04-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univinfo', '0002_univteam_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univteam',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
