# Generated by Django 4.2 on 2023-04-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univinfo', '0003_alter_univteam_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, max_length=500)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vheader', models.CharField(blank=True, max_length=100)),
                ('vision', models.TextField(blank=True, max_length=3000)),
                ('mheader', models.CharField(blank=True, max_length=100)),
                ('univmessage', models.TextField(blank=True, max_length=3000)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='UnivInfo/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='univteam',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
