# Generated by Django 4.2 on 2023-04-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univinfo', '0004_additionmessage_visionmessage_univteam_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionmessage',
            name='image',
            field=models.ImageField(blank=True, upload_to='vision/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='visionmessage',
            name='image',
            field=models.ImageField(blank=True, upload_to='Vision/%y/%m/%d'),
        ),
    ]
