# Generated by Django 4.2 on 2023-04-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univinfo', '0005_additionmessage_image_alter_visionmessage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditonalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(blank=True, max_length=30)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='AdditionalImage/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
