# Generated by Django 4.2 on 2023-04-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univinfo', '0006_additonalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additonalimage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
