# Generated by Django 4.2 on 2023-04-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univinfo', '0008_alter_additonalimage_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPresident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('Header', models.CharField(blank=True, max_length=100)),
                ('studying', models.TextField(blank=True, max_length=3000)),
                ('carrier', models.TextField(blank=True, max_length=3000)),
                ('image', models.ImageField(blank=True, upload_to='Board/%y/%m/%d')),
                ('date_created', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnivPresidentWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('Header', models.CharField(blank=True, max_length=100)),
                ('word', models.TextField(blank=True, max_length=3000)),
                ('image', models.ImageField(blank=True, upload_to='Univpresident/%y/%m/%d')),
                ('date_created', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='additionmessage',
            name='date_created',
            field=models.DateField(),
        ),
    ]
