# Generated by Django 4.1.5 on 2023-04-23 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('univinfo', '0009_boardpresident_univpresidentword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionmessage',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='additonalimage',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='univteam',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visionmessage',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
