# Generated by Django 4.1.5 on 2023-04-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univinfo', '0010_alter_additionmessage_date_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnivTeam',
        ),
        migrations.DeleteModel(
            name='VisionMessage',
        ),
    ]
