# Generated by Django 4.1.5 on 2023-04-23 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('univinfo', '0011_delete_univteam_delete_visionmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnivTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.IntegerField(null=True)),
                ('facebook', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='Team/%y/%m/%d')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vheader', models.CharField(blank=True, max_length=100)),
                ('vision', models.TextField(blank=True, max_length=3000)),
                ('mheader', models.CharField(blank=True, max_length=100)),
                ('univmessage', models.TextField(blank=True, max_length=3000)),
                ('image', models.ImageField(blank=True, upload_to='Vision/%y/%m/%d')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
