# Generated by Django 4.1.5 on 2023-05-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univinfo', '0012_univteam_visionmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='univteam',
            name='vision',
            field=models.TextField(default=' '),
        ),
    ]
