# Generated by Django 4.1.5 on 2023-05-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univinfo', '0013_univteam_vision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionmessage',
            options={'verbose_name': 'موضع إظافي', 'verbose_name_plural': 'موضوع إضافي'},
        ),
        migrations.AlterModelOptions(
            name='additonalimage',
            options={'verbose_name': 'صورة', 'verbose_name_plural': 'صور إظافية'},
        ),
        migrations.AlterModelOptions(
            name='boardpresident',
            options={'verbose_name': 'رئيس مجلس امناء', 'verbose_name_plural': 'رئيس مجلي الامناء'},
        ),
        migrations.AlterModelOptions(
            name='univpresidentword',
            options={'verbose_name': 'كلمة', 'verbose_name_plural': 'رئيس الجامعة'},
        ),
        migrations.AlterModelOptions(
            name='univteam',
            options={'verbose_name': 'كادر', 'verbose_name_plural': 'كادر الجامعة'},
        ),
        migrations.AlterModelOptions(
            name='visionmessage',
            options={'verbose_name': 'رؤية او رسالة', 'verbose_name_plural': 'الرؤية والرسالة'},
        ),
    ]
