# Generated by Django 4.1.5 on 2023-05-06 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('univinfo', '0014_alter_additionmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionmessage',
            name='image_ar',
            field=models.ImageField(blank=True, upload_to='vision/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='additionmessage',
            name='subject_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع'),
        ),
        migrations.AddField(
            model_name='additonalimage',
            name='image_ar',
            field=models.ImageField(blank=True, upload_to='AdditionalImage/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='additonalimage',
            name='photo_name_ar',
            field=models.CharField(blank=True, max_length=30, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='boardpresident',
            name='Header_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='boardpresident',
            name='carrier_ar',
            field=models.TextField(blank=True, max_length=3000, verbose_name='السجل الوظيفي'),
        ),
        migrations.AddField(
            model_name='boardpresident',
            name='image_ar',
            field=models.ImageField(blank=True, upload_to='Board/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='boardpresident',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='boardpresident',
            name='studying_ar',
            field=models.TextField(blank=True, max_length=3000, verbose_name='السجل الدراسي'),
        ),
        migrations.AddField(
            model_name='univpresidentword',
            name='Header_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='univpresidentword',
            name='image_ar',
            field=models.ImageField(blank=True, upload_to='Univpresident/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='univpresidentword',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='univpresidentword',
            name='word_ar',
            field=models.TextField(blank=True, max_length=3000, verbose_name='الكلمة'),
        ),
        migrations.AddField(
            model_name='univteam',
            name='email_ar',
            field=models.EmailField(blank=True, max_length=150, verbose_name='البريد'),
        ),
        migrations.AddField(
            model_name='univteam',
            name='facebook_ar',
            field=models.CharField(blank=True, max_length=150, verbose_name='الفيسبوك'),
        ),
        migrations.AddField(
            model_name='univteam',
            name='image_ar',
            field=models.ImageField(blank=True, upload_to='Team/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='univteam',
            name='job_ar',
            field=models.CharField(default=1, max_length=50, verbose_name='الوظيفة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='univteam',
            name='name_ar',
            field=models.CharField(default=1, max_length=100, verbose_name='الاسم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='univteam',
            name='phone_ar',
            field=models.IntegerField(null=True, verbose_name='الهاتف'),
        ),
        migrations.AddField(
            model_name='univteam',
            name='vision_ar',
            field=models.TextField(default=' ', verbose_name='الرؤية'),
        ),
        migrations.AddField(
            model_name='visionmessage',
            name='image_ar',
            field=models.ImageField(blank=True, upload_to='Vision/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='visionmessage',
            name='mheader_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان الرسالة'),
        ),
        migrations.AddField(
            model_name='visionmessage',
            name='univmessage_ar',
            field=models.TextField(blank=True, max_length=3000, verbose_name='رسالة الجامعة'),
        ),
        migrations.AddField(
            model_name='visionmessage',
            name='vheader_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان الرؤية'),
        ),
        migrations.AddField(
            model_name='visionmessage',
            name='vision_ar',
            field=models.TextField(blank=True, max_length=3000, verbose_name='الرؤية'),
        ),
        migrations.AlterField(
            model_name='additionmessage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='additionmessage',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='additionmessage',
            name='image',
            field=models.ImageField(blank=True, upload_to='vision/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='additionmessage',
            name='subject',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='additonalimage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='additonalimage',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='additonalimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='AdditionalImage/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='additonalimage',
            name='photo_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='boardpresident',
            name='Header',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='boardpresident',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='boardpresident',
            name='carrier',
            field=models.TextField(blank=True, max_length=3000, verbose_name='السجل الوظيفي'),
        ),
        migrations.AlterField(
            model_name='boardpresident',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='boardpresident',
            name='image',
            field=models.ImageField(blank=True, upload_to='Board/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='boardpresident',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='boardpresident',
            name='studying',
            field=models.TextField(blank=True, max_length=3000, verbose_name='السجل الدراسي'),
        ),
        migrations.AlterField(
            model_name='univpresidentword',
            name='Header',
            field=models.CharField(blank=True, max_length=100, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='univpresidentword',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='univpresidentword',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='univpresidentword',
            name='image',
            field=models.ImageField(blank=True, upload_to='Univpresident/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='univpresidentword',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='univpresidentword',
            name='word',
            field=models.TextField(blank=True, max_length=3000, verbose_name='الكلمة'),
        ),
        migrations.AlterField(
            model_name='univteam',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='univteam',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='univteam',
            name='email',
            field=models.EmailField(blank=True, max_length=150, verbose_name='البريد'),
        ),
        migrations.AlterField(
            model_name='univteam',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, verbose_name='الفيسبوك'),
        ),
        migrations.AlterField(
            model_name='univteam',
            name='image',
            field=models.ImageField(blank=True, upload_to='Team/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='univteam',
            name='job',
            field=models.CharField(max_length=50, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='univteam',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='univteam',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='univteam',
            name='vision',
            field=models.TextField(default=' ', verbose_name='الرؤية'),
        ),
        migrations.AlterField(
            model_name='visionmessage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='visionmessage',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='visionmessage',
            name='image',
            field=models.ImageField(blank=True, upload_to='Vision/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='visionmessage',
            name='mheader',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان الرسالة'),
        ),
        migrations.AlterField(
            model_name='visionmessage',
            name='univmessage',
            field=models.TextField(blank=True, max_length=3000, verbose_name='رسالة الجامعة'),
        ),
        migrations.AlterField(
            model_name='visionmessage',
            name='vheader',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان الرؤية'),
        ),
        migrations.AlterField(
            model_name='visionmessage',
            name='vision',
            field=models.TextField(blank=True, max_length=3000, verbose_name='الرؤية'),
        ),
    ]
