# Generated by Django 4.1.5 on 2023-04-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineerlab',
            old_name='name',
            new_name='collage_name',
        ),
        migrations.RenameField(
            model_name='medicinelab',
            old_name='name',
            new_name='collage_name',
        ),
        migrations.AddField(
            model_name='engineerlab',
            name='lab_name',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinelab',
            name='lab_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
