# Generated by Django 4.1.5 on 2023-04-23 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_rename_name_engineerlab_collage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerlab',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicinelab',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
