# Generated by Django 4.1.5 on 2023-04-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_engineerlab_date_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EngineerLab',
        ),
        migrations.DeleteModel(
            name='MedicineLab',
        ),
    ]
