# Generated by Django 4.1.5 on 2023-05-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineerlab',
            options={'verbose_name': 'مختبر', 'verbose_name_plural': 'مختبرات كلية الهندسة'},
        ),
        migrations.AlterModelOptions(
            name='medicinelab',
            options={'verbose_name': 'مختبر', 'verbose_name_plural': 'مختبرات كلية الطب'},
        ),
    ]
