# Generated by Django 4.1.5 on 2023-05-06 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_alter_engineerlab_options_alter_medicinelab_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinelab',
            name='date_created',
        ),
        migrations.AddField(
            model_name='engineerlab',
            name='collage_name_ar',
            field=models.CharField(default=1, max_length=100, verbose_name='اسم الكلية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engineerlab',
            name='description_ar',
            field=models.TextField(default=1, max_length=300, verbose_name='وصف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engineerlab',
            name='image_ar',
            field=models.ImageField(blank=True, upload_to='medicine/lib/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='engineerlab',
            name='lab_name_ar',
            field=models.CharField(default=1, max_length=100, verbose_name='اسم المختبر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinelab',
            name='collage_name_ar',
            field=models.CharField(default=1, max_length=100, verbose_name='اسم الكلية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinelab',
            name='date_created_ar',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AddField(
            model_name='medicinelab',
            name='description_ar',
            field=models.TextField(default=1, max_length=300, verbose_name='وصف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinelab',
            name='image_ar',
            field=models.ImageField(blank=True, upload_to='medicine/lib/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='medicinelab',
            name='lab_name_ar',
            field=models.CharField(default=1, max_length=100, verbose_name='اسم المختبر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engineerlab',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='engineerlab',
            name='collage_name',
            field=models.CharField(max_length=100, verbose_name='اسم الكلية'),
        ),
        migrations.AlterField(
            model_name='engineerlab',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='engineerlab',
            name='description',
            field=models.TextField(max_length=300, verbose_name='وصف'),
        ),
        migrations.AlterField(
            model_name='engineerlab',
            name='image',
            field=models.ImageField(blank=True, upload_to='medicine/lib/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='engineerlab',
            name='lab_name',
            field=models.CharField(max_length=100, verbose_name='اسم المختبر'),
        ),
        migrations.AlterField(
            model_name='medicinelab',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='medicinelab',
            name='collage_name',
            field=models.CharField(max_length=100, verbose_name='اسم الكلية'),
        ),
        migrations.AlterField(
            model_name='medicinelab',
            name='description',
            field=models.TextField(max_length=300, verbose_name='وصف'),
        ),
        migrations.AlterField(
            model_name='medicinelab',
            name='image',
            field=models.ImageField(blank=True, upload_to='medicine/lib/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='medicinelab',
            name='lab_name',
            field=models.CharField(max_length=100, verbose_name='اسم المختبر'),
        ),
    ]
