# Generated by Django 4.1.5 on 2023-04-22 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collage', '0008_collageengteam_collagemedteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=50)),
                ('nationality', models.CharField(max_length=150)),
                ('birth_place', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True)),
                ('high_school', models.CharField(choices=[('علمي', 'علمي'), ('ادبي', 'ادبي')], max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('certification_date', models.DateField(null=True)),
                ('certification_place', models.CharField(max_length=100)),
                ('governor', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('emission_place', models.CharField(max_length=50)),
                ('emission_date', models.DateField()),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('reationship', models.CharField(max_length=100)),
                ('his_phone', models.IntegerField()),
                ('major', models.CharField(choices=[('تقنية معلومات', 'تقنية معلومات'), ('هندسة معمارية', 'هندسة معماري'), ('هندسة مدنية', 'هندسة مدنية'), ('اتصالات', 'اتصالات'), ('هندسة معدات طبية', 'هندسة معدات طبية'), ('هندسة الميكا الكترونكس', 'هندسة الميكاالكترونكس'), ('هندسة النفط والغاز', 'هندسة النفط والغاز'), ('هندسة كيميائية', 'هندسة كيميائية'), ('هندسة مدنية', 'هندسة مدنية'), ('امن معلومات', 'امن معلومات'), ('صيدلة', 'صيدلة'), ('طب بشري', 'طب بشري'), ('مختبرات', 'مختبرات'), ('تمريض', 'تمريض'), ('طب اسنان', 'طب اسنان')], max_length=70)),
                ('id_card_type', models.CharField(choices=[('بطاقة شخصية', 'بطاقة شخصية'), ('بطاقة عائلية', 'بطاقة عائلية'), (' جواز', 'جواز ')], max_length=50)),
                ('card_number', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('collage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collage.collage')),
            ],
        ),
    ]
