# Generated by Django 4.1.5 on 2023-04-22 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentaff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='active',
        ),
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
