# Generated by Django 4.1.5 on 2023-04-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentaff', '0002_remove_student_active_alter_student_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='collage',
        ),
    ]
