# Generated by Django 4.1.5 on 2023-04-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentaff', '0006_alter_student_his_phone_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='ادخل الاسم'),
        ),
    ]
