# Generated by Django 4.1.5 on 2023-04-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentaff', '0007_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=150, verbose_name='الاسم'),
        ),
    ]
