# Generated by Django 4.1.5 on 2023-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentaff', '0009_remove_student_date_created_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('pdf', models.FileField(blank=True, upload_to='media/pdf')),
            ],
        ),
    ]
