# Generated by Django 4.1.5 on 2023-04-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentaff', '0010_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='pdf',
        ),
        migrations.AddField(
            model_name='schedule',
            name='image',
            field=models.FileField(blank=True, upload_to='media/schedule'),
        ),
    ]
