# Generated by Django 4.1.5 on 2023-04-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentaff', '0011_remove_schedule_pdf_schedule_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/schedule'),
        ),
    ]
