# Generated by Django 4.1.5 on 2023-04-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentaff', '0012_alter_schedule_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='image',
            field=models.ImageField(blank=True, upload_to='schedule/%y/%m/%d'),
        ),
    ]
