# Generated by Django 4.1.5 on 2023-04-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentaff', '0013_alter_schedule_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='name',
            new_name='collage_name',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='image',
            new_name='shcedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
