# Generated by Django 4.2 on 2023-04-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentaff', '0015_rename_shcedule_schedule_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
