# Generated by Django 4.1.5 on 2023-05-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentaff', '0018_alter_document_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='collage_name_ar',
            field=models.CharField(blank=True, max_length=40, verbose_name='الكلية'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_ar',
            field=models.FileField(default=1, upload_to='documents/', verbose_name='الجدول'),
            preserve_default=False,
        ),
    ]
