# Generated by Django 4.1.5 on 2023-05-17 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentaff', '0020_alter_student_gender_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_place',
            field=models.CharField(blank=True, max_length=50, verbose_name='Birth place'),
        ),
        migrations.AlterField(
            model_name='student',
            name='card_number',
            field=models.CharField(max_length=50, verbose_name='ID number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='certification_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Certification date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='certification_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Certification place'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='emission_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Emission place'),
        ),
        migrations.AlterField(
            model_name='student',
            name='emission_place',
            field=models.CharField(blank=True, max_length=50, verbose_name='Emission date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='governor',
            field=models.CharField(blank=True, max_length=50, verbose_name='governer'),
        ),
        migrations.AlterField(
            model_name='student',
            name='high_school',
            field=models.CharField(choices=[('علمي', 'علمي'), ('ادبي', 'ادبي')], max_length=50, verbose_name='High school ype'),
        ),
        migrations.AlterField(
            model_name='student',
            name='his_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Relationship Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_card_type',
            field=models.CharField(choices=[('بطاقة شخصية', 'بطاقة شخصية'), ('بطاقة عائلية', 'بطاقة عائلية'), (' جواز', 'جواز ')], max_length=50, verbose_name='ID type'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('تقنية معلومات', 'تقنية معلومات'), ('هندسة معمارية', 'هندسة معماري'), ('هندسة مدنية', 'هندسة مدنية'), ('اتصالات', 'اتصالات'), ('هندسة معدات طبية', 'هندسة معدات طبية'), ('هندسة الميكا الكترونكس', 'هندسة الميكاالكترونكس'), ('هندسة النفط والغاز', 'هندسة النفط والغاز'), ('هندسة كيميائية', 'هندسة كيميائية'), ('هندسة مدنية', 'هندسة مدنية'), ('امن معلومات', 'امن معلومات'), ('صيدلة', 'صيدلة'), ('طب بشري', 'طب بشري'), ('مختبرات', 'مختبرات'), ('تمريض', 'تمريض'), ('طب اسنان', 'طب اسنان')], max_length=70, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reationship',
            field=models.CharField(blank=True, max_length=100, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=50, verbose_name='School'),
        ),
    ]
