# Generated by Django 4.1.5 on 2023-05-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentaff', '0021_alter_student_address_alter_student_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='rate'),
        ),
    ]
