# Generated by Django 4.2 on 2023-04-21 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('vision', models.TextField(blank=True, max_length=3000)),
                ('message', models.TextField(blank=True, max_length=3000)),
                ('strategy', models.TextField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('image', models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='collage/%y/%m/%d')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('image', models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='collage/%y/%m/%d')),
                ('majorinfo', models.TextField(blank=True, max_length=3000)),
                ('goals', models.TextField(blank=True, max_length=300)),
                ('sectionunivinfo', models.TextField(blank=True, max_length=3000)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('collage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collage.collage')),
            ],
        ),
    ]
