# Generated by Django 4.2 on 2023-04-21 19:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('صيدلة', 'صيدلة'), ('طب بشري', 'طب بشري'), ('مختبرات', 'مختبرات'), ('تمريض', 'تمريض'), ('طب اسنان', 'طب اسنان')], max_length=50)),
                ('image', models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='collage/%y/%m/%d')),
                ('majorinfo', models.TextField(blank=True, max_length=3000)),
                ('goals', models.TextField(blank=True, max_length=300)),
                ('sectionunivinfo', models.TextField(blank=True, max_length=3000)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('collage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collage.collage')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('صيدلة', 'صيدلة'), ('طب بشري', 'طب بشري'), ('مختبرات', 'مختبرات'), ('تمريض', 'تمريض'), ('طب اسنان', 'طب اسنان')], max_length=50)),
                ('image', models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='collage/%y/%m/%d')),
                ('majorinfo', models.TextField(blank=True, max_length=3000)),
                ('goals', models.TextField(blank=True, max_length=300)),
                ('sectionunivinfo', models.TextField(blank=True, max_length=3000)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('collage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collage.collage')),
            ],
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
