# Generated by Django 4.2 on 2023-04-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0002_engineermajor_medicinemajor_delete_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineermajor',
            name='category',
            field=models.CharField(choices=[('تقنية معلومات', 'تقنية معلومات'), ('هندسة معمارية', 'هندسة معماري'), ('هندسة مدنية', 'هندسة مدنية'), ('اتصالات', 'اتصالات'), ('هندسة معدات طبية', 'هندسة معدات طبية'), ('هندسة الميكا الكترونكس', 'هندسة الميكاالكترونكس'), ('هندسة النفط والغاز', 'هندسة النفط والغاز'), ('هندسة كيميائية', 'هندسة كيميائية'), ('هندسة مدنية', 'هندسة مدنية'), ('امن معلومات', 'امن معلومات')], max_length=70),
        ),
        migrations.AlterField(
            model_name='engineermajor',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='ُEngineer/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='medicinemajor',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='medicine/%y/%m/%d'),
        ),
    ]
