# Generated by Django 4.2 on 2023-04-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0003_alter_engineermajor_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='vision/%y/%m/%d')),
                ('date_created', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdditonalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='AdditionalImage/%y/%m/%d')),
                ('date_created', models.DateField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
