# Generated by Django 4.2 on 2023-04-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0005_strategycollage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategycollage',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='medicine/%y/%m/%d'),
        ),
    ]
