# Generated by Django 4.1.5 on 2023-04-22 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0007_rename_strategycollage_strategyeng_strategymed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollageEngTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.IntegerField(null=True)),
                ('facebook', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='engTeam/%y/%m/%d')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollageMedTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.IntegerField(null=True)),
                ('facebook', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='medTeam/%y/%m/%d')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
