# Generated by Django 4.1.5 on 2023-04-23 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0008_collageengteam_collagemedteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionmessage',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='additonalimage',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
