# Generated by Django 4.1.5 on 2023-05-05 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0009_alter_additionmessage_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollageHumTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.IntegerField(null=True)),
                ('facebook', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='humTeam/%y/%m/%d')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'كادر',
                'verbose_name_plural': 'كادر كلية العلوم الانسانية',
            },
        ),
        migrations.AlterModelOptions(
            name='additionmessage',
            options={'verbose_name': 'رسالة إضافية', 'verbose_name_plural': 'رسائل إضافية'},
        ),
        migrations.AlterModelOptions(
            name='additonalimage',
            options={'verbose_name': 'صورة إظافية', 'verbose_name_plural': 'صور إظافية'},
        ),
        migrations.AlterModelOptions(
            name='collage',
            options={'verbose_name': 'كلية', 'verbose_name_plural': 'الكليات'},
        ),
        migrations.AlterModelOptions(
            name='collageengteam',
            options={'verbose_name': 'كادر', 'verbose_name_plural': 'كادر كلية الهندسة'},
        ),
        migrations.AlterModelOptions(
            name='collagemedteam',
            options={'verbose_name': 'كادر', 'verbose_name_plural': 'كادر كلية الطب'},
        ),
        migrations.AlterModelOptions(
            name='engineermajor',
            options={'verbose_name': 'كلية', 'verbose_name_plural': 'كلية الهندسة'},
        ),
        migrations.AlterModelOptions(
            name='medicinemajor',
            options={'verbose_name': 'تخصص', 'verbose_name_plural': 'كلية الطب'},
        ),
        migrations.AlterModelOptions(
            name='strategyeng',
            options={'verbose_name': 'إستراتيجية', 'verbose_name_plural': 'إستراتيجيةكلية الهندسة'},
        ),
        migrations.AlterModelOptions(
            name='strategymed',
            options={'verbose_name': 'إستراتيجية', 'verbose_name_plural': 'إستراتيجية كلية الطب'},
        ),
        migrations.CreateModel(
            name='StrategyHum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='Humanty/%y/%m/%d')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('collage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collage.collage')),
            ],
            options={
                'verbose_name': 'إستراتيجية',
                'verbose_name_plural': 'إستراتيجية كليةالعلوم',
            },
        ),
        migrations.CreateModel(
            name='HumanityMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('اللغات', 'اللغات'), ('علم النفس', 'علم النفس'), ('علم الاجتماع', 'علم الاجتماع'), ('الشريعة والدراسات الاسلامية', 'الشريعة والدراسات الاسلامية'), ('اللغة العربية', 'اللغة العربية'), ('قسم علم الاجتماع والخدمة الاجتماعية', 'قسم علم الاجتماع والخدمة الاجتماعية'), ('قسم الجغرافيا ونظم المعلومات الجغرافية', 'قسم الجغرافيا ونظم المعلومات الجغرافية'), ('قسم التاريــخ', 'قسم التاريــخ'), ('قسم علم الاجتماع والخدمة الاجتماعية', 'قسم علم الاجتماع والخدمة الاجتماعية')], max_length=70)),
                ('image', models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='Humanities/%y/%m/%d')),
                ('majorinfo', models.TextField(blank=True, max_length=3000)),
                ('goals', models.TextField(blank=True, max_length=300)),
                ('sectionunivinfo', models.TextField(blank=True, max_length=3000)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('collage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collage.collage')),
            ],
            options={
                'verbose_name': 'كلية',
                'verbose_name_plural': 'كلية العلوم الانسانية',
            },
        ),
    ]
