# Generated by Django 4.1.5 on 2023-05-05 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0010_collagehumteam_alter_additionmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionmessage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='additionmessage',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='additionmessage',
            name='image',
            field=models.ImageField(blank=True, upload_to='vision/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='additionmessage',
            name='subject',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='additonalimage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='additonalimage',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='additonalimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='AdditionalImage/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='additonalimage',
            name='photo_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='اسم الصورة'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='description',
            field=models.TextField(blank=True, max_length=400, verbose_name='وصف'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='collage/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='message',
            field=models.TextField(blank=True, max_length=3000, verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='strategy',
            field=models.TextField(blank=True, max_length=1000, verbose_name='الاستراتيجية'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='vision',
            field=models.TextField(blank=True, max_length=3000, verbose_name='الرؤية'),
        ),
        migrations.AlterField(
            model_name='collageengteam',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='collageengteam',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='collageengteam',
            name='email',
            field=models.EmailField(blank=True, max_length=150, verbose_name='البريد'),
        ),
        migrations.AlterField(
            model_name='collageengteam',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, verbose_name='الفيسبوك'),
        ),
        migrations.AlterField(
            model_name='collageengteam',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='engTeam/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='collageengteam',
            name='job',
            field=models.CharField(max_length=50, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='collageengteam',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='collageengteam',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='collagehumteam',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='collagehumteam',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='collagehumteam',
            name='email',
            field=models.EmailField(blank=True, max_length=150, verbose_name='البريد'),
        ),
        migrations.AlterField(
            model_name='collagehumteam',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, verbose_name='الفيسبوك'),
        ),
        migrations.AlterField(
            model_name='collagehumteam',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='humTeam/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='collagehumteam',
            name='job',
            field=models.CharField(max_length=50, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='collagehumteam',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='collagehumteam',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='collagemedteam',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='collagemedteam',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='collagemedteam',
            name='email',
            field=models.EmailField(blank=True, max_length=150, verbose_name='البريد'),
        ),
        migrations.AlterField(
            model_name='collagemedteam',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, verbose_name='الفيسبوك'),
        ),
        migrations.AlterField(
            model_name='collagemedteam',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='medTeam/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='collagemedteam',
            name='job',
            field=models.CharField(max_length=50, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='collagemedteam',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='collagemedteam',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='engineermajor',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='engineermajor',
            name='category',
            field=models.CharField(choices=[('تقنية معلومات', 'تقنية معلومات'), ('هندسة معمارية', 'هندسة معماري'), ('هندسة مدنية', 'هندسة مدنية'), ('اتصالات', 'اتصالات'), ('هندسة معدات طبية', 'هندسة معدات طبية'), ('هندسة الميكا الكترونكس', 'هندسة الميكاالكترونكس'), ('هندسة النفط والغاز', 'هندسة النفط والغاز'), ('هندسة كيميائية', 'هندسة كيميائية'), ('هندسة مدنية', 'هندسة مدنية'), ('امن معلومات', 'امن معلومات')], max_length=70, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='engineermajor',
            name='collage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collage.collage', verbose_name='الكلية'),
        ),
        migrations.AlterField(
            model_name='engineermajor',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='engineermajor',
            name='goals',
            field=models.TextField(blank=True, max_length=300, verbose_name='الاهداف'),
        ),
        migrations.AlterField(
            model_name='engineermajor',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='ُEngineer/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='engineermajor',
            name='majorinfo',
            field=models.TextField(blank=True, max_length=3000, verbose_name='معلومات التخصص'),
        ),
        migrations.AlterField(
            model_name='engineermajor',
            name='sectionunivinfo',
            field=models.TextField(blank=True, max_length=3000, verbose_name='معلومات القسم الجامعي'),
        ),
        migrations.AlterField(
            model_name='humanitymajor',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='humanitymajor',
            name='category',
            field=models.CharField(choices=[('اللغات', 'اللغات'), ('علم النفس', 'علم النفس'), ('علم الاجتماع', 'علم الاجتماع'), ('الشريعة والدراسات الاسلامية', 'الشريعة والدراسات الاسلامية'), ('اللغة العربية', 'اللغة العربية'), ('قسم علم الاجتماع والخدمة الاجتماعية', 'قسم علم الاجتماع والخدمة الاجتماعية'), ('قسم الجغرافيا ونظم المعلومات الجغرافية', 'قسم الجغرافيا ونظم المعلومات الجغرافية'), ('قسم التاريــخ', 'قسم التاريــخ'), ('قسم علم الاجتماع والخدمة الاجتماعية', 'قسم علم الاجتماع والخدمة الاجتماعية')], max_length=70, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='humanitymajor',
            name='collage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collage.collage', verbose_name='الكلية'),
        ),
        migrations.AlterField(
            model_name='humanitymajor',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='humanitymajor',
            name='goals',
            field=models.TextField(blank=True, max_length=300, verbose_name='الاهداف'),
        ),
        migrations.AlterField(
            model_name='humanitymajor',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='Humanities/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='humanitymajor',
            name='majorinfo',
            field=models.TextField(blank=True, max_length=3000, verbose_name='معلومات التخصص'),
        ),
        migrations.AlterField(
            model_name='humanitymajor',
            name='sectionunivinfo',
            field=models.TextField(blank=True, max_length=3000, verbose_name='معلومات القسم الجامعي'),
        ),
        migrations.AlterField(
            model_name='medicinemajor',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='medicinemajor',
            name='category',
            field=models.CharField(choices=[('صيدلة', 'صيدلة'), ('طب بشري', 'طب بشري'), ('مختبرات', 'مختبرات'), ('تمريض', 'تمريض'), ('طب اسنان', 'طب اسنان')], max_length=50, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='medicinemajor',
            name='collage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collage.collage', verbose_name='الكلية'),
        ),
        migrations.AlterField(
            model_name='medicinemajor',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='medicinemajor',
            name='goals',
            field=models.TextField(blank=True, max_length=300, verbose_name='الاهداف'),
        ),
        migrations.AlterField(
            model_name='medicinemajor',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='medicine/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='medicinemajor',
            name='majorinfo',
            field=models.TextField(blank=True, max_length=3000, verbose_name='معلومات التخصص'),
        ),
        migrations.AlterField(
            model_name='medicinemajor',
            name='sectionunivinfo',
            field=models.TextField(blank=True, max_length=3000, verbose_name='معلومات عن القسم الجامعي'),
        ),
        migrations.AlterField(
            model_name='strategyeng',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='strategyeng',
            name='collage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collage.collage', verbose_name='الكلية'),
        ),
        migrations.AlterField(
            model_name='strategyeng',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='strategyeng',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='medicine/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='strategyeng',
            name='subject',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='strategyhum',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='strategyhum',
            name='collage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collage.collage', verbose_name='الكلية '),
        ),
        migrations.AlterField(
            model_name='strategyhum',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='strategyhum',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='Humanty/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='strategyhum',
            name='subject',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='strategymed',
            name='active',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='strategymed',
            name='collage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collage.collage', verbose_name='الكلية'),
        ),
        migrations.AlterField(
            model_name='strategymed',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='strategymed',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='medicine/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='strategymed',
            name='subject',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع'),
        ),
    ]
