# Generated by Django 4.1.5 on 2023-05-06 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0011_alter_additionmessage_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinemajor',
            old_name='date_created',
            new_name='date_created_ar',
        ),
        migrations.AddField(
            model_name='additionmessage',
            name='image_ar',
            field=models.ImageField(blank=True, upload_to='vision/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='additionmessage',
            name='subject_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع'),
        ),
        migrations.AddField(
            model_name='additonalimage',
            name='image_ar',
            field=models.ImageField(blank=True, upload_to='AdditionalImage/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='additonalimage',
            name='photo_name_ar',
            field=models.CharField(blank=True, max_length=30, verbose_name='اسم الصورة'),
        ),
        migrations.AddField(
            model_name='collage',
            name='description_ar',
            field=models.TextField(blank=True, max_length=400, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='collage',
            name='image_ar',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='collage/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='collage',
            name='message_ar',
            field=models.TextField(blank=True, max_length=3000, verbose_name='الرسالة'),
        ),
        migrations.AddField(
            model_name='collage',
            name='name_ar',
            field=models.CharField(max_length=40, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='collage',
            name='strategy_ar',
            field=models.TextField(blank=True, max_length=1000, verbose_name='الاستراتيجية'),
        ),
        migrations.AddField(
            model_name='collage',
            name='vision_ar',
            field=models.TextField(blank=True, max_length=3000, verbose_name='الرؤية'),
        ),
        migrations.AddField(
            model_name='collageengteam',
            name='email_ar',
            field=models.EmailField(blank=True, max_length=150, verbose_name='البريد'),
        ),
        migrations.AddField(
            model_name='collageengteam',
            name='facebook_ar',
            field=models.CharField(blank=True, max_length=150, verbose_name='الفيسبوك'),
        ),
        migrations.AddField(
            model_name='collageengteam',
            name='image_ar',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='engTeam/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='collageengteam',
            name='job_ar',
            field=models.CharField(default=1, max_length=50, verbose_name='الوظيفة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collageengteam',
            name='name_ar',
            field=models.CharField(default=1, max_length=100, verbose_name='الاسم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collageengteam',
            name='phone_ar',
            field=models.IntegerField(null=True, verbose_name='الهاتف'),
        ),
        migrations.AddField(
            model_name='collagehumteam',
            name='email_ar',
            field=models.EmailField(blank=True, max_length=150, verbose_name='البريد'),
        ),
        migrations.AddField(
            model_name='collagehumteam',
            name='facebook_ar',
            field=models.CharField(blank=True, max_length=150, verbose_name='الفيسبوك'),
        ),
        migrations.AddField(
            model_name='collagehumteam',
            name='image_ar',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='humTeam/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='collagehumteam',
            name='job_ar',
            field=models.CharField(default=1, max_length=50, verbose_name='الوظيفة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collagehumteam',
            name='name_ar',
            field=models.CharField(default=1, max_length=100, verbose_name='الاسم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collagemedteam',
            name='email_ar',
            field=models.EmailField(blank=True, max_length=150, verbose_name='البريد'),
        ),
        migrations.AddField(
            model_name='collagemedteam',
            name='facebook_ar',
            field=models.CharField(blank=True, max_length=150, verbose_name='الفيسبوك'),
        ),
        migrations.AddField(
            model_name='collagemedteam',
            name='image_ar',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='medTeam/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='collagemedteam',
            name='job_ar',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='الوظيفة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collagemedteam',
            name='name_ar',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='الاسم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collagemedteam',
            name='phone_ar',
            field=models.IntegerField(null=True, verbose_name='الهاتف'),
        ),
        migrations.AddField(
            model_name='engineermajor',
            name='category_ar',
            field=models.CharField(choices=[('تقنية معلومات', 'تقنية معلومات'), ('هندسة معمارية', 'هندسة معماري'), ('هندسة مدنية', 'هندسة مدنية'), ('اتصالات', 'اتصالات'), ('هندسة معدات طبية', 'هندسة معدات طبية'), ('هندسة الميكا الكترونكس', 'هندسة الميكاالكترونكس'), ('هندسة النفط والغاز', 'هندسة النفط والغاز'), ('هندسة كيميائية', 'هندسة كيميائية'), ('هندسة مدنية', 'هندسة مدنية'), ('امن معلومات', 'امن معلومات')], default=django.utils.timezone.now, max_length=70, verbose_name='التخصص'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engineermajor',
            name='goals_ar',
            field=models.TextField(blank=True, max_length=300, verbose_name='الاهداف'),
        ),
        migrations.AddField(
            model_name='engineermajor',
            name='image_ar',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='ُEngineer/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='engineermajor',
            name='majorinfo_ar',
            field=models.TextField(blank=True, max_length=3000, verbose_name='معلومات التخصص'),
        ),
        migrations.AddField(
            model_name='engineermajor',
            name='sectionunivinfo_ar',
            field=models.TextField(blank=True, max_length=3000, verbose_name='معلومات القسم الجامعي'),
        ),
        migrations.AddField(
            model_name='humanitymajor',
            name='category_ar',
            field=models.CharField(choices=[('اللغات', 'اللغات'), ('علم النفس', 'علم النفس'), ('علم الاجتماع', 'علم الاجتماع'), ('الشريعة والدراسات الاسلامية', 'الشريعة والدراسات الاسلامية'), ('اللغة العربية', 'اللغة العربية'), ('قسم علم الاجتماع والخدمة الاجتماعية', 'قسم علم الاجتماع والخدمة الاجتماعية'), ('قسم الجغرافيا ونظم المعلومات الجغرافية', 'قسم الجغرافيا ونظم المعلومات الجغرافية'), ('قسم التاريــخ', 'قسم التاريــخ'), ('قسم علم الاجتماع والخدمة الاجتماعية', 'قسم علم الاجتماع والخدمة الاجتماعية')], default=1, max_length=70, verbose_name='التخصص'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humanitymajor',
            name='goals_ar',
            field=models.TextField(blank=True, max_length=300, verbose_name='الاهداف'),
        ),
        migrations.AddField(
            model_name='humanitymajor',
            name='image_ar',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='Humanities/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='humanitymajor',
            name='majorinfo_ar',
            field=models.TextField(blank=True, max_length=3000, verbose_name='معلومات التخصص'),
        ),
        migrations.AddField(
            model_name='humanitymajor',
            name='sectionunivinfo_ar',
            field=models.TextField(blank=True, max_length=3000, verbose_name='معلومات القسم الجامعي'),
        ),
        migrations.AddField(
            model_name='medicinemajor',
            name='category_ar',
            field=models.CharField(choices=[('صيدلة', 'صيدلة'), ('طب بشري', 'طب بشري'), ('مختبرات', 'مختبرات'), ('تمريض', 'تمريض'), ('طب اسنان', 'طب اسنان')], default=1, max_length=50, verbose_name='التخصص'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinemajor',
            name='goals_ar',
            field=models.TextField(blank=True, max_length=300, verbose_name='الاهداف'),
        ),
        migrations.AddField(
            model_name='medicinemajor',
            name='image_ar',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='medicine/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='medicinemajor',
            name='majorinfo_ar',
            field=models.TextField(blank=True, max_length=3000, verbose_name='معلومات التخصص'),
        ),
        migrations.AddField(
            model_name='medicinemajor',
            name='sectionunivinfo_ar',
            field=models.TextField(blank=True, max_length=3000, verbose_name='معلومات عن القسم الجامعي'),
        ),
        migrations.AddField(
            model_name='strategyeng',
            name='image_ar',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='medicine/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='strategyeng',
            name='subject_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع'),
        ),
        migrations.AddField(
            model_name='strategyhum',
            name='image_ar',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='Humanty/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='strategyhum',
            name='subject_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع'),
        ),
        migrations.AddField(
            model_name='strategymed',
            name='image_ar',
            field=models.ImageField(blank=True, default='/static/assets/img/hero-bg.jpg', upload_to='medicine/%y/%m/%d', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='strategymed',
            name='subject_ar',
            field=models.TextField(blank=True, max_length=500, verbose_name='موضوع'),
        ),
    ]
